# Generated by Django 5.0.4 on 2026-04-24 19:47

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('valid_from', models.DateTimeField(verbose_name='valid from')),
                ('valid_to', models.DateTimeField(verbose_name='valid to')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20, verbose_name='discount type')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount value')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum order amount')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum discount amount')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used.', null=True, verbose_name='maximum uses')),
                ('uses', models.PositiveIntegerField(default=0, verbose_name='uses')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('users', models.ManyToManyField(blank=True, help_text='Leave empty if coupon is valid for all users.', to=settings.AUTH_USER_MODEL, verbose_name='valid users')),
            ],
            options={
                'verbose_name': 'coupon',
                'verbose_name_plural': 'coupons',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['code'], name='coupon_coup_code_e43490_idx'), models.Index(fields=['valid_from', 'valid_to'], name='coupon_coup_valid_f_8bd8dc_idx')],
            },
        ),
    ]
