# Generated by Django 5.0.4 on 2026-04-23 21:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created'], 'verbose_name': 'coupon', 'verbose_name_plural': 'coupons'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=20, verbose_name='discount type'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='discount value'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='maximum discount amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used.', null=True, verbose_name='maximum uses'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='minimum order amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Leave empty if coupon is valid for all users.', to=settings.AUTH_USER_MODEL, verbose_name='valid users'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='uses',
            field=models.PositiveIntegerField(default=0, verbose_name='uses'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(verbose_name='valid to'),
        ),
    ]
