# Generated by Django 5.0.4 on 2026-05-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_status_changed', 'Order Status Changed'), ('shipment_updated', 'Shipment Updated'), ('stock_adjusted', 'Stock Adjusted'), ('coupon_created', 'Coupon Created'), ('coupon_updated', 'Coupon Updated'), ('coupon_deleted', 'Coupon Deleted'), ('bulk_action', 'Bulk Action'), ('invoice_generated', 'Invoice Generated')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='staff_staff_timesta_a041ca_idx'), models.Index(fields=['staff_user', '-timestamp'], name='staff_staff_staff_u_47a045_idx'), models.Index(fields=['action', '-timestamp'], name='staff_staff_action_91c9ba_idx')],
            },
        ),
    ]
