# Generated by Django 5.0.4 on 2026-05-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivitylog',
            name='action',
            field=models.CharField(choices=[('order_status_changed', 'Order Status Changed'), ('shipment_updated', 'Shipment Updated'), ('stock_adjusted', 'Stock Adjusted'), ('coupon_created', 'Coupon Created'), ('coupon_updated', 'Coupon Updated'), ('coupon_deleted', 'Coupon Deleted'), ('bulk_action', 'Bulk Action'), ('invoice_generated', 'Invoice Generated'), ('report_viewed', 'Report Viewed')], max_length=50),
        ),
    ]
