# Generated by Django 5.0.4 on 2026-05-13 01:07

import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staffactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivitylog',
            name='action',
            field=models.CharField(choices=[('order_status_changed', 'Order Status Changed'), ('shipment_updated', 'Shipment Updated'), ('stock_adjusted', 'Stock Adjusted'), ('coupon_created', 'Coupon Created'), ('coupon_updated', 'Coupon Updated'), ('coupon_deleted', 'Coupon Deleted'), ('bulk_action', 'Bulk Action'), ('invoice_generated', 'Invoice Generated'), ('report_viewed', 'Report Viewed'), ('customer_viewed', 'Customer Viewed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffactivitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, validators=[staff.models.validate_metadata_size, staff.models.validate_metadata_structure]),
        ),
    ]
