"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import environ

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent

# Locale
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

# Load environment variables
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY
SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-key")

DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Environment detection
IS_LOCAL = DEBUG

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cart.apps.CartConfig",
    "orders.apps.OrdersConfig",
    "shop.apps.ShopConfig",
    "payment.apps.PaymentConfig",
    "coupon.apps.CouponConfig",
    "myshop.core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Language detection happens here
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "myshop.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
                "myshop.core.context_processors.labels",
                "shop.context_processors.digits.digit_mode",
            ],
        },
    },
]

WSGI_APPLICATION = "myshop.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGES = [
    ("en", "English"),
    ("fa", "Persian"),
    # Example future languages:
    # ('de', 'German'),
    # ('fr', 'French'),
]

# keep default admin in English
LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# During development, Django loads from STATICFILES_DIRS
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# This folder is ONLY used when running: python manage.py collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Media Settings
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CART_SESSION_ID = "cart"

# Email Settings
if DEBUG:
    # DEVELOPMENT OPTION 1 — Console backend (default)
    # EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

    # DEVELOPMENT OPTION 2 — File backend (uncomment when testing attachments)
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    EMAIL_FILE_PATH = BASE_DIR / "sent_emails"
    DEFAULT_FROM_EMAIL = "webshop@example.com"
else:
    # PRODUCTION — Real SMTP
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    EMAIL_HOST_USER = "your-email@gmail.com"
    EMAIL_HOST_PASSWORD = "your-app-password"

# Celery
CELERY_BROKER_URL = "redis://localhost:6379/0"

# -----------------------
# Payment Gateway Settings
# -----------------------

PAYMENT_GATEWAYS = {
    "fake": {
        "NAME": "Fake Gateway",
    },
    "zibal": {
        "NAME": "Zibal Gateway",
        "MERCHANT": env(
            "ZIBAL_MERCHANT_TEST" if DEBUG else "ZIBAL_MERCHANT_REAL",
            default="ZIBAL" if DEBUG else "",
        ),
        "REQUEST_URL": ("https://gateway.zibal.ir/v1/request"),
        "VERIFY_URL": ("https://gateway.zibal.ir/v1/verify"),
        "STARTPAY_URL": ("https://gateway.zibal.ir/start/"),
    },
    "zarinpal": {
        "NAME": "Zarinpal Gateway",
        "MERCHANT_ID": env(
            "ZARINPAL_MERCHANT_TEST" if DEBUG else "ZARINPAL_MERCHANT_REAL",
            default="" if not DEBUG else "123e4567-e89b-12d3-a456-426614174000",
        ),
        "REQUEST_URL": (
            "https://sandbox.zarinpal.com/pg/v4/payment/request.json"
            if DEBUG
            else "https://api.zarinpal.com/pg/v4/payment/request.json"
        ),
        "VERIFY_URL": (
            "https://sandbox.zarinpal.com/pg/v4/payment/verify.json"
            if DEBUG
            else "https://api.zarinpal.com/pg/v4/payment/verify.json"
        ),
        "STARTPAY_URL": (
            "https://sandbox.zarinpal.com/pg/StartPay/"
            if DEBUG
            else "https://www.zarinpal.com/pg/StartPay/"
        ),
    },
}

# Currency Settings
CURRENCY_CODE = "IRR"
CURRENCY_SYMBOLS = {
    "fa": "تومان",
    "en": "Toman",
}

# Invoice / Order labels (RTL friendly)
ORDER_LABELS = {
    "total_amount": "مبلغ کل",
    "customer_label": "نام مشتری",
    "order_label": "شماره سفارش",
    "date_label": "تاریخ سفارش",
    "products_title": "محصولات",
    "product_name": "نام محصول",
    "quantity": "تعداد",
    "price": "قیمت",
    "sum": "جمع",
    # Fake Bank
    "fake_bank_title": "درگاه تست",
    "fake_bank_amount_label": "مبلغ پرداخت",
    "fake_bank_choose_result": "نتیجه پرداخت را انتخاب کنید",
    "fake_bank_successful_payment": "پرداخت موفق",
    "fake_bank_cancel_payment": "انصراف از پرداخت",
    "checkout": "ادامه",
    # Failure Page
    "payment_success_title": "پرداخت موفق",
    "payment_failed_title": "پرداخت ناموفق",
    "payment_cancelled_title": "پرداخت لغو شد",
    "payment_failed_message": "متأسفانه پرداخت شما انجام نشد یا توسط بانک لغو شد.",
    "payment_cancelled_message": "پرداخت توسط شما لغو شد.",
    "tracking_code": "کد پیگیری",
    "back_to_shop": "بازگشت به فروشگاه",
    "back_to_cart": "بازگشت به سبد خرید",
    "no_amount_deducted": "مبلغی از حساب شما کسر نشده است.",
    # Coupon
    "coupon_label": "کد تخفیف",
    "discount_label": "میزان تخفیف",
    "final_amount_label": "مبلغ نهایی",
    "subtotal_label": "جمع جزء",
    "discount_title": "تخفیف خرید",
    "final_amount_title": "مبلغ قابل پرداخت",
    # Invoice
    "invoice_label": "فاکتور",
    "invoice_number_label": "شماره فاکتور",
    "order_id_label": "شماره سفارش",
    "items_label": "آیتم‌ها",
    "total_label": "مبلغ نهایی",
    "footer_label": "با تشکر از خرید شما",
    "paid_label": "پرداخت شده",
    "unpaid_label": "پرداخت نشده",
}

# --- Shop UI Labels ---
SHOP_LABELS = {
    "product_list_title": "محصولات",
    "categories_title": "دسته بندی‌ها",
    "all_products": "همه محصولات",
    "add_to_cart": "افزودن به سبد خرید",
    "your_cart": "سبد خرید شما",
    "item_singular": "کالا",
    "item_plural": "کالاها",
    "cart_total": "جمع کل",
    "cart_empty": "سبد خرید شما خالی است.",
    "continue_shopping": "ادامه خرید",
    "checkout": "ثبت و پرداخت",
    "product_detail_title": "جزئیات محصول",
    "price_label": "قیمت",
    "quantity_label": "تعداد",
}

# Default currency symbol (used by PDF generator)
CURRENCY_SYMBOL = "تومان"
