# Generated by Django 5.0.4 on 2026-04-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_shop_produc_slug_76971b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional variant-specific price', max_digits=20, null=True, verbose_name='price override')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product variant',
                'verbose_name_plural': 'product variants',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
