# Generated by Django 5.0.4 on 2026-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_sync_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
