# Generated by Django 5.0.4 on 2026-05-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_canonical_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'stock'], name='shop_produc_availab_707188_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'stock'], name='shop_produc_product_187aaf_idx'),
        ),
    ]
