# Generated by Django 5.0.4 on 2026-05-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_shop_produc_availab_707188_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional variant-specific image', upload_to='variants/%Y/%m/%d', verbose_name='variant image'),
        ),
    ]
