# Generated by Django 5.0.4 on 2026-05-05 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_search_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, help_text='For anonymous users', max_length=40, verbose_name='session key')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='viewed at')),
            ],
            options={
                'verbose_name': 'product view',
                'verbose_name_plural': 'product views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='last_purchased',
            field=models.DateTimeField(blank=True, help_text='Last time this product was purchased', null=True, verbose_name='last purchased'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this product has been purchased', verbose_name='purchase count'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times this product has been viewed', verbose_name='view count'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-purchase_count'], name='shop_produc_purchas_ece0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-view_count'], name='shop_produc_view_co_d61403_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-last_purchased'], name='shop_produc_last_pu_a027a0_idx'),
        ),
        migrations.AddField(
            model_name='productview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='shop.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='productview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['product', '-viewed_at'], name='shop_produc_product_0cb44c_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['user', '-viewed_at'], name='shop_produc_user_id_14a9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='productview',
            index=models.Index(fields=['session_key', '-viewed_at'], name='shop_produc_session_66af6b_idx'),
        ),
    ]
