# Generated by Django 5.0.4 on 2026-05-07 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_stockalert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockalert',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='stockalert',
            old_name='created',
            new_name='created_at',
        ),
    ]
