# Generated by Django 5.0.4 on 2026-04-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation_status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], default='reserved', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
