# Generated by Django 5.0.4 on 2026-04-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('packaging', 'Packaging'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_processing',
            field=models.BooleanField(default=False, help_text='Prevents multiple simultaneous payment verifications'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='payment reference ID'),
        ),
    ]
