# Generated by Django 5.0.4 on 2026-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
