# Generated by Django 5.0.4 on 2026-04-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.BigIntegerField(default=0),
        ),
    ]
