# Generated by Django 5.0.4 on 2026-04-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='payment status'),
        ),
    ]
