# Generated by Django 5.0.4 on 2026-04-30 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'Order created'), ('stock_reserved', 'Stock reserved'), ('payment_requested', 'Payment requested'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('item_cancelled', 'Item cancelled'), ('refund_requested', 'Refund requested'), ('refund_approved', 'Refund approved'), ('refund_completed', 'Refund completed'), ('shipment_created', 'Shipment created'), ('order_shipped', 'Order shipped'), ('tracking_added', 'Tracking added')], max_length=50)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
