# Generated by Django 5.0.4 on 2026-05-02 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderevent'),
        ('shop', '0006_alter_product_canonical_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.productvariant'),
        ),
    ]
