# Generated by Django 5.0.4 on 2026-05-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderevent_options_orderitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='type',
            field=models.CharField(choices=[('order_created', 'Order created'), ('stock_reserved', 'Stock reserved'), ('stock_restored', 'Stock restored'), ('payment_requested', 'Payment requested'), ('payment_success', 'Payment successful'), ('payment_failed', 'Payment failed'), ('item_cancelled', 'Item cancelled'), ('refund_requested', 'Refund requested'), ('refund_approved', 'Refund approved'), ('refund_completed', 'Refund completed'), ('shipment_created', 'Shipment created'), ('order_shipped', 'Order shipped'), ('tracking_added', 'Tracking added')], max_length=50),
        ),
    ]
